name: A workflow for my Hello Vikas file
on: push
jobs:
  build:
    name: Hello vikas action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Vikas"
